"""Permissions and action policies for AURA v0.7.0.

The LLM never grants these permissions. Policies are owned by deterministic code.
"""
from dataclasses import dataclass
from enum import Enum

from security.risk import RiskLevel


class Permission(str, Enum):
    READ_LOCAL_DATA = "read_local_data"
    WRITE_LOCAL_DATA = "write_local_data"
    DELETE_LOCAL_RECORDS = "delete_local_records"
    FILESYSTEM_DELETE = "filesystem_delete"
    EXTERNAL_NETWORK = "external_network"
    WEB_READ = "web_read"
    BROWSER_MUTATE = "browser_mutate"
    BROWSER_DOWNLOAD = "browser_download"
    LOCATION_ACCESS = "location_access"
    # P0.6.2.8 — separate allowlisted app launch from arbitrary process control.
    SAFE_APP_LAUNCH = "safe_app_launch"
    # P0.6.5.1 — scoped access to the explicit authorized-folder registry.
    AUTHORIZED_FOLDER_ACCESS = "authorized_folder_access"
    # P0.6.5.2 — content read is separate from folder open/list permissions.
    AUTHORIZED_FILE_READ = "authorized_file_read"
    PROCESS_CONTROL = "process_control"
    SYSTEM_CHANGE = "system_change"
    SECRET_ACCESS = "secret_access"


@dataclass(frozen=True)
class ActionPolicy:
    risk: RiskLevel
    permission: Permission
    confirmation_required: bool = False


# Current v0.4 actions plus reserved policies for future capabilities.
ACTION_POLICIES: dict[str, ActionPolicy] = {
    "LIST_MEMORIES": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "SEARCH_MEMORY": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "ANSWER_MEMORY_QUERY": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "EXPLAIN_MEMORY": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "MEMORY_STATUS": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    # P0.6.2.7 — read-only local system/runtime telemetry. This does not
    # grant process control, filesystem deletion, system change or secret access.
    "SYSTEM_STATUS": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    # Only fixed built-in application IDs can reach this action. Arbitrary
    # executable names, arguments, paths and shells remain under RUN_PROGRAM.
    "OPEN_SAFE_APP": ActionPolicy(RiskLevel.LOW, Permission.SAFE_APP_LAUNCH),
    # P0.6.5.1 — raw paths can only reach AUTHORIZE_FOLDER. OPEN/LIST use
    # opaque ids from SystemService's persistent registry.
    "AUTHORIZE_FOLDER": ActionPolicy(
        RiskLevel.MEDIUM, Permission.AUTHORIZED_FOLDER_ACCESS, True
    ),
    "REVOKE_AUTHORIZED_FOLDER": ActionPolicy(
        RiskLevel.MEDIUM, Permission.AUTHORIZED_FOLDER_ACCESS, True
    ),
    "LIST_AUTHORIZED_FOLDER": ActionPolicy(
        RiskLevel.SAFE, Permission.AUTHORIZED_FOLDER_ACCESS
    ),
    "OPEN_AUTHORIZED_FOLDER": ActionPolicy(
        RiskLevel.LOW, Permission.AUTHORIZED_FOLDER_ACCESS, True
    ),
    # Only direct-child file ids generated by SystemService can reach this.
    "READ_AUTHORIZED_FILE": ActionPolicy(
        RiskLevel.SAFE, Permission.AUTHORIZED_FILE_READ
    ),
    # P0.6.5.3 — deterministic local analysis reuses authorized_file_read.
    "ANALYZE_AUTHORIZED_FILE": ActionPolicy(
        RiskLevel.SAFE, Permission.AUTHORIZED_FILE_READ
    ),
    # P0.6.5.4 — multi-file project intelligence is still bounded local read.
    "ANALYZE_AUTHORIZED_PROJECT": ActionPolicy(
        RiskLevel.SAFE, Permission.AUTHORIZED_FILE_READ
    ),
    "CREATE_MEMORY": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "SET_MEMORY_PRIVATE_MODE": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "SET_MEMORY_NORMAL_MODE": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "FORGET_MEMORY": ActionPolicy(RiskLevel.MEDIUM, Permission.DELETE_LOCAL_RECORDS),
    "FORGET_MEMORY_ALL": ActionPolicy(RiskLevel.MEDIUM, Permission.DELETE_LOCAL_RECORDS),
    "FORGET_ALL_MEMORIES": ActionPolicy(RiskLevel.MEDIUM, Permission.DELETE_LOCAL_RECORDS),
    "LIST_NOTES": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "SEARCH_NOTE": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "LIST_TASKS": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "LIST_REMINDERS": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "CREATE_NOTE": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "CREATE_TASK": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "COMPLETE_TASK": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    "CREATE_REMINDER": ActionPolicy(RiskLevel.LOW, Permission.WRITE_LOCAL_DATA),
    # App-level record deletion is explicit and auditable. It remains MEDIUM in
    # v0.4.1 so existing note/reminder behavior stays compatible.
    "DELETE_NOTE": ActionPolicy(RiskLevel.MEDIUM, Permission.DELETE_LOCAL_RECORDS),
    "DELETE_REMINDER": ActionPolicy(RiskLevel.MEDIUM, Permission.DELETE_LOCAL_RECORDS),
    # Future capabilities: declared now so they fail safely before executors exist.
    "WEB_REQUEST": ActionPolicy(RiskLevel.MEDIUM, Permission.EXTERNAL_NETWORK),
    "WEB_WEATHER": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "WEB_SEARCH": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "WEB_FETCH": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    # v0.7.0.15.6.12.1: map/geocoding requests supplied by the user are
    # read-only network actions. They do not reveal the device position.
    "MAPS_LOCATE": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "MAPS_DIRECTIONS": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "MAPS_OPEN_EXTERNAL": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    # Current-device location is deliberately separate and is NOT granted by
    # default. Future geolocation must request this permission explicitly.
    "LOCATION_CURRENT": ActionPolicy(RiskLevel.MEDIUM, Permission.LOCATION_ACCESS, True),
    "KNOWLEDGE_REFERENCE_LOCAL": ActionPolicy(RiskLevel.SAFE, Permission.READ_LOCAL_DATA),
    "WEB_KNOWLEDGE_REFERENCE": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "RUN_PROGRAM": ActionPolicy(RiskLevel.HIGH, Permission.PROCESS_CONTROL, True),
    "DELETE_FILE": ActionPolicy(RiskLevel.HIGH, Permission.FILESYSTEM_DELETE, True),
    "SEND_EMAIL": ActionPolicy(RiskLevel.HIGH, Permission.EXTERNAL_NETWORK, True),
    "INSTALL_SOFTWARE": ActionPolicy(RiskLevel.HIGH, Permission.SYSTEM_CHANGE, True),
    "MODIFY_SYSTEM": ActionPolicy(RiskLevel.HIGH, Permission.SYSTEM_CHANGE, True),
    "DISABLE_SECURITY": ActionPolicy(RiskLevel.CRITICAL, Permission.SYSTEM_CHANGE, True),
    "READ_SECRET": ActionPolicy(RiskLevel.CRITICAL, Permission.SECRET_ACCESS, True),
}


# Permissions enabled by default. v0.7.0 adds WEB_READ for controlled network tools;
# process/system/secret capabilities remain disabled.
DEFAULT_GRANTED_PERMISSIONS: frozenset[Permission] = frozenset(
    {
        Permission.READ_LOCAL_DATA,
        Permission.WRITE_LOCAL_DATA,
        Permission.DELETE_LOCAL_RECORDS,
        # P0.6.2.8 permits only SystemService's fixed safe-app allowlist.
        # It does NOT grant PROCESS_CONTROL and therefore cannot authorize
        # arbitrary RUN_PROGRAM operations.
        Permission.SAFE_APP_LAUNCH,
        Permission.AUTHORIZED_FOLDER_ACCESS,
        Permission.AUTHORIZED_FILE_READ,
        # v0.7.0 grants read-only external network access to deterministic tools.
        # High-risk network actions (e.g. SEND_EMAIL) still require confirmation.
        Permission.WEB_READ,
    }
)

# AURA_V096_BROWSER_SECURITY_MAPPING_BEGIN
# Read-only browser actions reuse WEB_READ.
ACTION_POLICIES.update({
    "BROWSER_OPEN": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "BROWSER_NAVIGATE": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "BROWSER_READ": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "BROWSER_EXTRACT": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "BROWSER_SEARCH": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
    "BROWSER_CLICK": ActionPolicy(RiskLevel.MEDIUM, Permission.BROWSER_MUTATE, True),
    "BROWSER_FILL": ActionPolicy(RiskLevel.MEDIUM, Permission.BROWSER_MUTATE, True),
    "BROWSER_SUBMIT": ActionPolicy(RiskLevel.MEDIUM, Permission.BROWSER_MUTATE, True),
    "BROWSER_DOWNLOAD": ActionPolicy(RiskLevel.MEDIUM, Permission.BROWSER_DOWNLOAD, True),
    "BROWSER_WORKFLOW": ActionPolicy(RiskLevel.LOW, Permission.WEB_READ),
})
# AURA_V096_BROWSER_SECURITY_MAPPING_END
