"""Unicode/Markdown-safe response text normalization for AURA UI.

Patch 26.8.8 extends the 26.8.6 display boundary with a conservative
Markdown-math sanitizer. Gemini can emit inline TeX such as ``$\\rightarrow$``;
Qt's QTextDocument Markdown renderer does not render LaTeX math, so those
control sequences were previously visible to the user as odd characters.
"""
from __future__ import annotations

import html
import re
import unicodedata

# Typical UTF-8 -> Latin-1/Windows-1252 corruption markers.
_MOJIBAKE_MARKERS = (
    "Ã", "Â", "â€", "â€™", "â€œ", "â€\x9d", "â€“", "â€”", "â€¢", "â€¦",
    "ðŸ", "ï»¿", "ï¿½", "�",
)

# Invisible controls that may alter reading order or visual layout. Keep ZWJ
# (U+200D) because it is legitimate inside emoji sequences.
_STRIP_CODEPOINTS = {
    0xFEFF,  # BOM / zero width no-break space
    0x200B,  # zero width space
    0x2060,  # word joiner
    0x202A, 0x202B, 0x202C, 0x202D, 0x202E,  # bidi embedding/override
    0x2066, 0x2067, 0x2068, 0x2069,          # bidi isolates
}

# QTextDocument.setMarkdown() intentionally does not implement a TeX math
# engine. Convert the small set of mathematical commands LLMs commonly use in
# prose to their Unicode equivalents before handing the text to Qt.
_TEX_SYMBOLS = {
    r"\rightarrow": "→",
    r"\to": "→",
    r"\longrightarrow": "→",
    r"\leftarrow": "←",
    r"\longleftarrow": "←",
    r"\leftrightarrow": "↔",
    r"\Rightarrow": "⇒",
    r"\Leftarrow": "⇐",
    r"\Leftrightarrow": "⇔",
    r"\geq": "≥",
    r"\ge": "≥",
    r"\leq": "≤",
    r"\le": "≤",
    r"\neq": "≠",
    r"\ne": "≠",
    r"\approx": "≈",
    r"\times": "×",
    r"\cdot": "·",
    r"\pm": "±",
    r"\mp": "∓",
    r"\infty": "∞",
    r"\degree": "°",
    r"\bullet": "•",
    r"\checkmark": "✓",
}


def _mojibake_score(value: str) -> int:
    score = sum(value.count(marker) for marker in _MOJIBAKE_MARKERS)
    # C1 controls are a strong sign of UTF-8 bytes decoded as Latin-1.
    score += sum(2 for ch in value if 0x80 <= ord(ch) <= 0x9F)
    return score


def repair_mojibake(value: str) -> str:
    """Repair UTF-8 text accidentally decoded through a single-byte codec.

    The repair is conservative: a candidate is accepted only when it reduces
    the mojibake score. Normal French such as ``Âge`` therefore stays untouched.
    """
    original = str(value or "")
    best = original
    best_score = _mojibake_score(original)
    if best_score <= 0:
        return original

    for codec in ("latin-1", "cp1252"):
        try:
            candidate = original.encode(codec).decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            continue
        candidate_score = _mojibake_score(candidate)
        if candidate_score < best_score:
            best = candidate
            best_score = candidate_score
    return best


def normalize_unicode_text(text: str, *, unescape_html: bool = False) -> str:
    """Return stable NFC Unicode suitable for Qt text widgets."""
    value = str(text or "")
    if not value:
        return ""

    value = value.replace("\r\n", "\n").replace("\r", "\n")
    value = repair_mojibake(value)
    if unescape_html:
        value = html.unescape(value)

    # Normalize spacing characters that often look like broken gaps in Qt.
    value = value.replace("\u00a0", " ").replace("\u202f", " ")
    value = value.replace("\u2028", "\n").replace("\u2029", "\n")
    value = "".join(ch for ch in value if ord(ch) not in _STRIP_CODEPOINTS)

    # Drop non-whitespace C0/C1 controls but preserve newlines/tabs.
    cleaned: list[str] = []
    for ch in value:
        code = ord(ch)
        if ch in "\n\t":
            cleaned.append(ch)
            continue
        if code < 0x20 or 0x7F <= code <= 0x9F:
            continue
        cleaned.append(ch)

    value = unicodedata.normalize("NFC", "".join(cleaned))
    value = re.sub(r"[ \t]+(?=\n)", "", value)
    value = re.sub(r"\n{4,}", "\n\n\n", value)
    return value.strip()


def _plain_tex_fragment(fragment: str) -> str:
    """Turn simple LLM-generated inline TeX into readable Unicode text.

    This is deliberately *not* a TeX renderer. It only handles presentation
    artifacts that are useful in normal prose and leaves unknown content
    readable rather than exposing dollar delimiters around it.
    """
    value = str(fragment or "").strip()
    if not value:
        return ""

    # Common wrappers generated by Gemini in otherwise normal prose.
    value = re.sub(r"\\text\s*\{([^{}]*)\}", r"\1", value)
    value = re.sub(r"\\mathrm\s*\{([^{}]*)\}", r"\1", value)
    value = re.sub(r"\\mathbf\s*\{([^{}]*)\}", r"\1", value)
    value = re.sub(r"\\operatorname\s*\{([^{}]*)\}", r"\1", value)

    # Longer commands first so that e.g. \longrightarrow is not partially
    # changed by a shorter suffix.
    for command in sorted(_TEX_SYMBOLS, key=len, reverse=True):
        value = value.replace(command, _TEX_SYMBOLS[command])

    # Standard escaped punctuation in model output.
    value = value.replace(r"\%", "%").replace(r"\_", "_")
    value = value.replace(r"\&", "&").replace(r"\#", "#")

    # Remove cosmetic TeX spacing commands when present.
    for spacing in (r"\,", r"\;", r"\:", r"\!"):
        value = value.replace(spacing, " ")
    value = re.sub(r"\\(?:quad|qquad)\b", " ", value)
    value = re.sub(r"[ \t]{2,}", " ", value)
    return value.strip()


def normalize_markdown_math(text: str) -> str:
    """Remove unsupported TeX delimiters/commands from Markdown prose.

    Examples:
      ``réarmement $\\rightarrow$ aucun défaut`` -> ``réarmement → aucun défaut``
      ``$T \\geq 30$`` -> ``T ≥ 30``

    Currency such as ``10 $`` is not touched because only balanced math
    delimiters are processed.
    """
    value = str(text or "")
    if not value:
        return ""

    # Display math first, then inline math. Dot does not cross newlines for the
    # inline form, which avoids consuming large Markdown sections accidentally.
    value = re.sub(
        r"\$\$\s*([\s\S]{1,500}?)\s*\$\$",
        lambda m: _plain_tex_fragment(m.group(1)),
        value,
    )
    value = re.sub(
        r"(?<!\\)\$([^\n$]{1,220}?)(?<!\\)\$",
        lambda m: _plain_tex_fragment(m.group(1)),
        value,
    )

    # Some providers emit a bare command without dollar delimiters. Convert
    # only the known harmless commands; unknown backslash content is preserved.
    for command in sorted(_TEX_SYMBOLS, key=len, reverse=True):
        value = value.replace(command, _TEX_SYMBOLS[command])
    return value


def normalize_markdown_text(text: str) -> str:
    """Normalize model Markdown while keeping supported Markdown syntax."""
    value = normalize_unicode_text(text, unescape_html=False)
    value = normalize_markdown_math(value)
    return normalize_unicode_text(value, unescape_html=False)


def normalize_plain_text(text: str) -> str:
    """Normalize legacy rich-text fragments for a plain Unicode widget."""
    value = normalize_unicode_text(text, unescape_html=True)
    value = normalize_markdown_math(value)
    value = re.sub(r"(?i)<\s*br\s*/?\s*>", "\n", value)
    value = re.sub(r"(?i)</\s*(?:p|div|li|pre)\s*>", "\n", value)
    value = re.sub(r"(?i)<\s*li(?:\s+[^>]*)?>", "• ", value)
    value = re.sub(r"(?i)<\s*(?:p|div|ul|ol|pre)(?:\s+[^>]*)?>", "", value)
    value = re.sub(r"(?i)</?\s*(?:b|strong|i|em|span|code)(?:\s+[^>]*)?>", "", value)
    value = re.sub(r"[ \t]+(?=\n)", "", value)
    value = re.sub(r"\n{3,}", "\n\n", value)
    return value.strip()
